SELECT
  YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
  (B.MAX_DEV - A.SIZE_OF_COLONY) AS YEAR_DEV,
  A.ID
FROM ECOLI_DATA A
JOIN (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS Y,
    MAX(SIZE_OF_COLONY) AS MAX_DEV
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) B
  ON YEAR(A.DIFFERENTIATION_DATE) = B.Y
ORDER BY YEAR ASC, YEAR_DEV ASC;
