-- 코드를 작성해주세요
SELECT A.ID AS ID, B.FISH_NAME AS FISH_NAME, A.LENGTH AS LENGTH FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN FROM FISH_INFO GROUP BY FISH_TYPE) M
ON A.FISH_TYPE = M.FISH_TYPE
AND A.LENGTH = M.MAX_LEN
ORDER BY A.ID ASC;